name: Check build

on: ["push", "pull_request"]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: sudo apt update && sudo apt install -qy python-is-python3 python3-numpy cmake libosmesa6-dev
      - name: Configure
        run: cmake -B build -S . -DCMAKE_BUILD_TYPE=Release
      - name: Build
        run: cmake --build build
      - name: test
        run: PYTHONPATH=build python -c "import bop_renderer"
